### ISSUE TITLE
translateY轴计算错误，不知道为什么

### ISSUE THREAD

**Issue by shmilybaozi** [shenyWill/vue-virtual-cascader#11]
![image](https://github.com/shenyWill/vue-virtual-cascader/assets/36563636/f2d6b4b0-bd29-453a-bec3-ee4109d9af85)

**Comment by shmilybaozi** [comment]
找到原因了，是我自己的数据问题

**Comment by shenyWill** [comment]
最新的源码刚刚已经上传
